Repository Geekups/telegram-boors-gold-dollar-bot, pull requests merged in 2024-04, with the labels that each got.

#4 add todo
  0-Bamdada-Todo.txt
  1-Mostafa-Todo.txt
  requirements.txt
Labels: documentation, enhancement

#5 Fixed a number of bugs and performed tasks requested by Bamdad
  reg.py
  requirements.txt
  start and admin.py
  stock.py
Labels: bug, documentation, enhancement

#7 fix name
  anonsurf_handler.py
Labels: bug, documentation

#8 add bs4 request for stock
  stock.py
  stock_info.py
Labels: bug, enhancement

#9 web scrapping
  3-Guide.txt
  get_dollar_and_gold.py
Labels: enhancement, help wanted

#10 Submit the final project
  anonsurf_handler.py
  get_dollar_and_gold.py
  main.py
  requirements.txt
  send_to_channel.py
  start_and_admin.py
  stock.py
  stock_info.py
  targets.xlsx
Labels: documentation, enhancement

#12 Final edit
  .github/workflows/python-app.yml
  get_dollar_and_gold.py
  main.py
  requirements.txt
Labels: bug

#13 check it man
  main.py
Labels: documentation, enhancement

#14 oskol on coda tahe get_dollar...py vase test bood ghrboonet beram
  get_dollar_and_gold.py
Labels: bug, duplicate

#15 Fixed the problem of running files at the same time
  get_dollar_and_gold.py
  main.py
  reg.py
  send_to_channel.py
  start_and_admin.py
  stock.py
  stock_info.py
Labels: bug, documentation, enhancement
